package particleswarm;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author saadel
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private int nbTaches = 0;
    private int nbMachines = 0;
    private String ordre = "";
    private double duree = 0;

    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableOfInput = new javax.swing.JTable();
        nbMachinesLabel = new javax.swing.JLabel();
        nbMachinesField = new javax.swing.JTextField();
        nbTachesLabel = new javax.swing.JLabel();
        nbTachesField = new javax.swing.JTextField();
        validerButton = new javax.swing.JButton();
        betaField = new javax.swing.JTextField();
        omegaField = new javax.swing.JTextField();
        c1Field = new javax.swing.JTextField();
        c2Field = new javax.swing.JTextField();
        resultatButton = new javax.swing.JButton();
        diagrammeButton = new javax.swing.JButton();
        tempsMinLabel = new javax.swing.JLabel();
        ordreTachesLabel = new javax.swing.JLabel();
        betaLabel = new javax.swing.JLabel();
        omegaLabel = new javax.swing.JLabel();
        c1Label = new javax.swing.JLabel();
        c2Label = new javax.swing.JLabel();
        lireCSVButton = new javax.swing.JButton();
        parametresLabel = new javax.swing.JLabel();
        nbIterationsField = new javax.swing.JTextField();
        nbIterationsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableOfInput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Machine", "Tâche", "Temps"
            }
        ));
        jScrollPane1.setViewportView(tableOfInput);

        nbMachinesLabel.setText("Nombre de machines");

        nbMachinesField.setColumns(12);
        nbMachinesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbMachinesFieldActionPerformed(evt);
            }
        });

        nbTachesLabel.setText("Nombre de tâches");

        nbTachesField.setColumns(12);
        nbTachesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbTachesFieldActionPerformed(evt);
            }
        });

        validerButton.setText("Valider");
        validerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerButtonActionPerformed(evt);
            }
        });

        betaField.setColumns(8);
        betaField.setText("0.975");
        betaField.setToolTipText("");
        betaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betaFieldActionPerformed(evt);
            }
        });

        omegaField.setColumns(8);
        omegaField.setText("1.2");
        omegaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                omegaFieldActionPerformed(evt);
            }
        });

        c1Field.setColumns(8);
        c1Field.setText("2");
        c1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1FieldActionPerformed(evt);
            }
        });

        c2Field.setColumns(8);
        c2Field.setText("2");

        resultatButton.setText("Générer le résultat");
        resultatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultatButtonActionPerformed(evt);
            }
        });

        diagrammeButton.setText("Générer le diagramme");
        diagrammeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagrammeButtonActionPerformed(evt);
            }
        });

        tempsMinLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        tempsMinLabel.setText("Temps Minimum:");

        ordreTachesLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ordreTachesLabel.setText("Ordre des tâches:");

        betaLabel.setText("Beta:");

        omegaLabel.setText("Omega:");

        c1Label.setText("c1:");

        c2Label.setText("c2:");

        lireCSVButton.setText("Lire depuis un fichier CSV");
        lireCSVButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lireCSVButtonActionPerformed(evt);
            }
        });

        parametresLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        parametresLabel.setText("Paramètres de l'algorithme:");

        nbIterationsField.setColumns(8);
        nbIterationsField.setText("10");
        nbIterationsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbIterationsFieldActionPerformed(evt);
            }
        });

        nbIterationsLabel.setText("Nombre d'itérations:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(validerButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(parametresLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lireCSVButton)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nbTachesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nbTachesLabel)
                                            .addComponent(nbMachinesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nbMachinesLabel))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(omegaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(omegaLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nbIterationsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(betaLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(nbIterationsLabel))
                                    .addComponent(betaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(c1Label)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c2Label))))
                        .addGap(163, 163, 163)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resultatButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(diagrammeButton)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ordreTachesLabel)
                                .addComponent(tempsMinLabel)))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ordreTachesLabel, tempsMinLabel});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {c2Field, omegaField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nbMachinesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nbMachinesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nbTachesLabel))
                            .addComponent(validerButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nbTachesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lireCSVButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diagrammeButton)
                            .addComponent(resultatButton))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(parametresLabel)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(betaLabel)
                            .addComponent(omegaLabel))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(betaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(omegaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(c1Label)
                                    .addComponent(c2Label))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(c1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addComponent(nbIterationsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nbIterationsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(ordreTachesLabel))))
                    .addComponent(tempsMinLabel))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nbMachinesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbMachinesFieldActionPerformed
        
        
    }//GEN-LAST:event_nbMachinesFieldActionPerformed

    private void betaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_betaFieldActionPerformed

    private void diagrammeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagrammeButtonActionPerformed

        
        
    }//GEN-LAST:event_diagrammeButtonActionPerformed

    private void nbTachesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbTachesFieldActionPerformed
        
    }//GEN-LAST:event_nbTachesFieldActionPerformed

    private void validerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerButtonActionPerformed

        try {
            nbTaches = Integer.parseInt(nbTachesField.getText());
            nbMachines = Integer.parseInt(nbMachinesField.getText());
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Veuillez entrer un numéro valide", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
//        System.out.println(nbMachines + "  " + nbTaches);
        
        DefaultTableModel model = new DefaultTableModel();  
        model.addColumn("Machine"); 
        model.addColumn("Tâche");
        model.addColumn("Temps");
        for (int i=1; i<=nbMachines ; i++)
            for (int j=1; j<=nbTaches ; j++)
            {
                String Jb = "T"+j;
                String Mc = "M"+i;
                model.addRow(new Object[]{Mc,Jb});
            }
        tableOfInput.setModel(model);
    }//GEN-LAST:event_validerButtonActionPerformed

    public double[][] getTableData (JTable table) {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        double Matrice[][] = new double[nbTaches][nbMachines];
        int itr=0;
        for (int i = 0 ; i<nbMachines ; i++)
        {
            for (int j = 0 ; j <nbTaches ; j++)
            {
                if (dtm.getValueAt(itr,2)==null) return null;
                Matrice[j][i] = Double.parseDouble(dtm.getValueAt(itr,2).toString());
                itr++;
            }

        }
        return Matrice;
    }
        
    private void resultatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultatButtonActionPerformed
        
        double omega = 1.2;
        double beta = 0.975;
        double c1 = 2;
        double c2 = 2;
        int nbIterations = 0;
        
        try {
            omega = Double.parseDouble(omegaField.getText());
            beta = Double.parseDouble(betaField.getText());
            c1 = Double.parseDouble(c1Field.getText());
            c2 = Double.parseDouble(c2Field.getText());
            nbIterations = Integer.parseInt(nbIterationsField.getText());
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Veuillez entrer un numéro valide", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        
        PSO pso= new PSO(nbTaches, nbMachines);
        
        pso.setBetha(beta);
        pso.setC1(c1);
        pso.setC2(c2);
        pso.setW0(omega);
        
        

        double mat[][] = getTableData(tableOfInput);
//
//        for(int i=0;i<nbTaches;i++)
//        {
//            for(int j=0;j<nbMachines;j++)
//            {
//                System.out.print(mat[i][j]+" ");
//            }
//            System.out.println();
//        }
        
        pso.setInitialJobs(mat);
        pso.initialise();
        pso.findPermutaion();
        pso.initialiseBestP();
        pso.findPersonaleBest();
        pso.findGloabalBest();

        for(int i=0;i<nbIterations;i++)
        {
            pso.generateXV();
            pso.findPermutaion();
            pso.completionTime();
            pso.findPersonaleBest();
            pso.findGloabalBest();  
        }
        DecimalFormat df = new DecimalFormat("#");
//        System.out.println(pso.getFg());
        ordre = "";
        for(int i=0;i<pso.getN();i++)
            ordre += df.format(pso.getG()[i]) + " ";
        
        duree = pso.getFg();
        this.tempsMinLabel.setText("Temps Minimum: " + pso.getFg());        
        this.ordreTachesLabel.setText("Ordre des tâches: " + ordre);
        
    }//GEN-LAST:event_resultatButtonActionPerformed

    private void nbIterationsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbIterationsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbIterationsFieldActionPerformed

    private void omegaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_omegaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_omegaFieldActionPerformed

    private void c1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1FieldActionPerformed

    private void lireCSVButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lireCSVButtonActionPerformed
        
        String csvFile = "data.csv";
	BufferedReader br = null;
	String line = "";
	String cvsSplitBy = ",";
        
        double matr[][] = new double[nbTaches][nbMachines];
	
        try {
                
		br = new BufferedReader(new FileReader(csvFile));
                int j = 0;
                while ((line = br.readLine()) != null) {
                    String[] split = line.split(cvsSplitBy);
//                    System.out.println(split[0] + split[1] + split.length);
                    for (int i = 0; i < split.length; i++) {
                        matr[j][i] = Double.parseDouble(split[i]);
                        System.out.println(matr[j][i]);
                    }
                    j++;
		}
 
	} catch (FileNotFoundException e) {
		e.printStackTrace();
	} catch (IOException e) {
		e.printStackTrace();
	} finally {
		if (br != null) {
			try {
				br.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
	}
        for (int i = 0; i < nbTaches; i++) {
            for (int j = 0; j < nbMachines; j++) {
                System.out.println("--     " + matr[i][j]);
            }
        }
        
        DefaultTableModel model = new DefaultTableModel();  
        model.addColumn("Machine"); 
        model.addColumn("Tâche");
        model.addColumn("Temps");
        for (int i=0; i<nbMachines ; i++)
            for (int j=0; j<nbTaches ; j++)
            {
                String Jb = "T" + (j+1);
                String Mc = "M" + (i+1);
                String temps = matr[j][i] + "";
                System.out.println("  " + matr[j][i]);
                model.addRow(new Object[]{Mc,Jb,temps});
            }
        tableOfInput.setModel(model);
    }//GEN-LAST:event_lireCSVButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField betaField;
    private javax.swing.JLabel betaLabel;
    private javax.swing.JTextField c1Field;
    private javax.swing.JLabel c1Label;
    private javax.swing.JTextField c2Field;
    private javax.swing.JLabel c2Label;
    private javax.swing.JButton diagrammeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lireCSVButton;
    private javax.swing.JTextField nbIterationsField;
    private javax.swing.JLabel nbIterationsLabel;
    private javax.swing.JTextField nbMachinesField;
    private javax.swing.JLabel nbMachinesLabel;
    private javax.swing.JTextField nbTachesField;
    private javax.swing.JLabel nbTachesLabel;
    private javax.swing.JTextField omegaField;
    private javax.swing.JLabel omegaLabel;
    private javax.swing.JLabel ordreTachesLabel;
    private javax.swing.JLabel parametresLabel;
    private javax.swing.JButton resultatButton;
    private javax.swing.JTable tableOfInput;
    private javax.swing.JLabel tempsMinLabel;
    private javax.swing.JButton validerButton;
    // End of variables declaration//GEN-END:variables
}
